### PR TITLE
add support for aarch64

### PR DESCRIPTION
**Pull request by blackliner**

### CODE REVIEW

**Comment by Warchant** [comment]
I really hope that you tested it :)

**Comment by blackliner** [comment]
> I really hope that you tested it :)

Sorry for the late reply, yes I tested it on a MacBook M3 Pro. Not about the existing logic for Windows or Linux arm though 🙈

**Comment by blackliner** [comment]
A tag would be very welcome. We use the sha for now, and it works well 👍

**Comment by pziggo** [comment]
I can also confirm, while having issues with `rev: 0.1.1`:
```
    raise NotImplementedError(f"Target CPU/OS is not supported: {platform.machine()}")
NotImplementedError: Target CPU/OS is not supported: aarch64
```

`rev: 497e2c5c3183d84db54eb4fd2613feab34da6dce` works for me as well. @blackliner , thanks for the fix.

**Comment by Warchant** [comment]
https://github.com/Warchant/pre-commit-buildifier/releases/tag/0.1.2

**Comment by blackliner** [comment]
Not sure what is going on, but my system is failing again, same error as above. Should have used machine() instead of processor() I guess?

**Comment by Warchant** [comment]
@blackliner what is the output of 

```
import platform
platform.processor().lower()
```

**Comment by Warchant** [comment]
https://github.com/Warchant/pre-commit-buildifier/releases/tag/0.1.3

**Pull request merged**
